//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 11/20/2024 11:25:10 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EasyAFModel.Core;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Restier.Core.Authorization;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace EasyAFTests.Api
{

    /// <summary>
    /// 
    /// </summary>
    public static class EasyAFEntitiesAuthorizationConfig
    {
    
        #region Public Methods
        
        /// <summary>
        ///
        /// </summary>
        public static void Configure()
        {
            bool trueAction() => true;
            bool adminAction() => ClaimsPrincipal.Current.IsInRole("Admin");
            
            var entries = new List<AuthorizationEntry>
            {
                new AuthorizationEntry(typeof(Inquiry), trueAction, adminAction, adminAction),
                new AuthorizationEntry(typeof(InquiryStateType), trueAction, adminAction, adminAction),
                new AuthorizationEntry(typeof(Product), trueAction, adminAction, adminAction),
                new AuthorizationEntry(typeof(ProductStatusType), trueAction, adminAction, adminAction),
                new AuthorizationEntry(typeof(User), trueAction, adminAction, adminAction),
            };
            AuthorizationFactory.RegisterEntries(entries);
        }
        
        #endregion
        
    }
    
}
