namespace Microsoft.Extensions.DependencyInjection
{

    /// <summary>
    /// A set of extensions for registering the {{Product}} business layer into an <see cref="IServiceCollection" />.
    /// </summary>
    public static class {{Product}}_Business_IServiceCollectionExtensions
    {

        /// <summary>
        /// Registers the {{Product}} business managers with the <see cref="IServiceCollection" />.
        /// </summary>
        /// <param name="services">The <see cref="IServiceCollection" /> instance to register the managers with.</param>
        /// <returns>The passed-in <see cref="IServiceCollection" /> instance for fluent chaining.</returns>
        public static IServiceCollection Add{{Product}}Business(this IServiceCollection services)
        {
            // TODO: Register the managers generated by `dotnet easyaf code generate`, for example:
            //services.AddScoped<CustomerManager>();

            return services;
        }

    }

}
