//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 9/14/2026 3:48:07 AM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.EasyAF.Core;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EasyAFModel
{

    public partial class Inquiry : DbObservableObject, IHasState<InquiryStateType>, ICreatedAuditable, ICreatorTrackable<Guid>, IUpdatedAuditable, IUpdaterTrackable<Guid>
    {
    
        #region Private Members
        
        private Guid _createdById;
        private DateTimeOffset _dateCreated;
        private Nullable<DateTimeOffset> _dateUpdated;
        private Guid _id;
        private string _message;
        private Guid _stateTypeId;
        private string _subject;
        private Nullable<Guid> _updatedById;
        private InquiryStateType _stateType;
        private User _user;
        
        #endregion
        
        #region Public Properties
        
        public Guid Id
        {
            get => _id;
            set => Set(() => Id, ref _id, value);
        }
        
        [StringLength(200)]
        public string Subject
        {
            get => _subject;
            set => Set(() => Subject, ref _subject, value);
        }
        
        [StringLength(1000)]
        public string Message
        {
            get => _message;
            set => Set(() => Message, ref _message, value);
        }
        
        public Guid StateTypeId
        {
            get => _stateTypeId;
            set => Set(() => StateTypeId, ref _stateTypeId, value);
        }
        
        public Guid CreatedById
        {
            get => _createdById;
            set => Set(() => CreatedById, ref _createdById, value);
        }
        
        public DateTimeOffset DateCreated
        {
            get => _dateCreated;
            set => Set(() => DateCreated, ref _dateCreated, value);
        }
        
        public Nullable<Guid> UpdatedById
        {
            get => _updatedById;
            set => Set(() => UpdatedById, ref _updatedById, value);
        }
        
        public Nullable<DateTimeOffset> DateUpdated
        {
            get => _dateUpdated;
            set => Set(() => DateUpdated, ref _dateUpdated, value);
        }
        
        public InquiryStateType StateType
        {
            get => _stateType;
            set => Set(() => StateType, ref _stateType, value);
        }
        
        public User User
        {
            get => _user;
            set => Set(() => User, ref _user, value);
        }
        
        #endregion
        
        #region Constructors
        
        public Inquiry()
        {
        }
        
        #endregion
        
    }
    
}
