//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 11/20/2024 11:32:38 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.EasyAF.Core;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EasyAFModel
{

    /// <summary>
    /// 
    /// </summary>
    public partial class Product : DbObservableObject, IHasStatus<ProductStatusType>, ICreatedAuditable, ICreatorTrackable<Guid>, IUpdatedAuditable, IUpdaterTrackable<Guid>
    {
    
        #region Private Members
        
        private Guid _createdById;
        private DateTimeOffset _dateCreated;
        private Nullable<DateTimeOffset> _dateUpdated;
        private string _displayName;
        private Guid _id;
        private Guid _statusTypeId;
        private Nullable<Guid> _updatedById;
        private ProductStatusType _statusType;
        
        #endregion
        
        #region Public Properties
        
        /// <summary>
        /// 
        /// </summary>
        public Guid Id
        {
            get => _id;
            set => Set(() => Id, ref _id, value);
        }
        
        /// <summary>
        /// 
        /// </summary>
        [StringLength(50)]
        public string DisplayName
        {
            get => _displayName;
            set => Set(() => DisplayName, ref _displayName, value);
        }
        
        /// <summary>
        /// 
        /// </summary>
        public Guid StatusTypeId
        {
            get => _statusTypeId;
            set => Set(() => StatusTypeId, ref _statusTypeId, value);
        }
        
        /// <summary>
        /// 
        /// </summary>
        public Guid CreatedById
        {
            get => _createdById;
            set => Set(() => CreatedById, ref _createdById, value);
        }
        
        /// <summary>
        /// 
        /// </summary>
        public DateTimeOffset DateCreated
        {
            get => _dateCreated;
            set => Set(() => DateCreated, ref _dateCreated, value);
        }
        
        /// <summary>
        /// 
        /// </summary>
        public Nullable<Guid> UpdatedById
        {
            get => _updatedById;
            set => Set(() => UpdatedById, ref _updatedById, value);
        }
        
        /// <summary>
        /// 
        /// </summary>
        public Nullable<DateTimeOffset> DateUpdated
        {
            get => _dateUpdated;
            set => Set(() => DateUpdated, ref _dateUpdated, value);
        }
        
        /// <summary>
        /// 
        /// </summary>
        public ProductStatusType StatusType
        {
            get => _statusType;
            set => Set(() => StatusType, ref _statusType, value);
        }
        
        #endregion
        
        #region Constructors
        
        /// <summary>
        /// 
        /// </summary>
        public Product()
        {
        }
        
        #endregion
        
    }
    
}
