//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 9/28/2026 12:59:15 AM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.EasyAF.Core;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EasyAFModel
{

    public partial class ProductStatusType : DbObservableObject, IDbStatusEnum, ICreatedAuditable, IUpdatedAuditable, IUpdaterTrackable<Guid>
    {
    
        #region Private Members
        
        private Nullable<Guid> _createdById;
        private DateTimeOffset _dateCreated;
        private Nullable<DateTimeOffset> _dateUpdated;
        private string _displayName;
        private Guid _id;
        private bool _isActive;
        private int _sortOrder;
        private Nullable<Guid> _updatedById;
        private ObservableCollection<Product> _products;
        
        #endregion
        
        #region Public Properties
        
        public Guid Id
        {
            get => _id;
            set => Set(nameof(Id), ref _id, value);
        }
        
        [StringLength(50)]
        public string DisplayName
        {
            get => _displayName;
            set => Set(nameof(DisplayName), ref _displayName, value);
        }
        
        public int SortOrder
        {
            get => _sortOrder;
            set => Set(nameof(SortOrder), ref _sortOrder, value);
        }
        
        public bool IsActive
        {
            get => _isActive;
            set => Set(nameof(IsActive), ref _isActive, value);
        }
        
        public Nullable<Guid> CreatedById
        {
            get => _createdById;
            set => Set(nameof(CreatedById), ref _createdById, value);
        }
        
        public DateTimeOffset DateCreated
        {
            get => _dateCreated;
            set => Set(nameof(DateCreated), ref _dateCreated, value);
        }
        
        public Nullable<Guid> UpdatedById
        {
            get => _updatedById;
            set => Set(nameof(UpdatedById), ref _updatedById, value);
        }
        
        public Nullable<DateTimeOffset> DateUpdated
        {
            get => _dateUpdated;
            set => Set(nameof(DateUpdated), ref _dateUpdated, value);
        }
        
        public ObservableCollection<Product> Products
        {
            get => _products;
            set => Set(nameof(Products), ref _products, value);
        }
        
        #endregion
        
        #region Constructors
        
        public ProductStatusType()
        {
        }
        
        #endregion
        
    }
    
}
