//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 11/20/2024 11:32:38 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.EasyAF.Core;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EasyAFModel
{

    /// <summary>
    /// 
    /// </summary>
    public partial class User : DbObservableObject, IIdentifiable<Guid>, ICreatedAuditable, ICreatorTrackable<Guid>
    {
    
        #region Private Members
        
        private Guid _createdById;
        private DateTimeOffset _dateCreated;
        private string _firstName;
        private Guid _id;
        private string _lastName;
        private ObservableCollection<Inquiry> _inquiries;
        
        #endregion
        
        #region Public Properties
        
        /// <summary>
        /// 
        /// </summary>
        public Guid Id
        {
            get => _id;
            set => Set(() => Id, ref _id, value);
        }
        
        /// <summary>
        /// 
        /// </summary>
        [StringLength(30)]
        public string FirstName
        {
            get => _firstName;
            set => Set(() => FirstName, ref _firstName, value);
        }
        
        /// <summary>
        /// 
        /// </summary>
        [StringLength(50)]
        public string LastName
        {
            get => _lastName;
            set => Set(() => LastName, ref _lastName, value);
        }
        
        /// <summary>
        /// 
        /// </summary>
        public Guid CreatedById
        {
            get => _createdById;
            set => Set(() => CreatedById, ref _createdById, value);
        }
        
        /// <summary>
        /// 
        /// </summary>
        public DateTimeOffset DateCreated
        {
            get => _dateCreated;
            set => Set(() => DateCreated, ref _dateCreated, value);
        }
        
        /// <summary>
        /// 
        /// </summary>
        public ObservableCollection<Inquiry> Inquiries
        {
            get => _inquiries;
            set => Set(() => Inquiries, ref _inquiries, value);
        }
        
        #endregion
        
        #region Constructors
        
        /// <summary>
        /// 
        /// </summary>
        public User()
        {
        }
        
        #endregion
        
    }
    
}
