//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 11/20/2024 11:28:15 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EasyAFModel.Core;
using Microsoft.AspNet.OData.Builder;
using Microsoft.OData.Edm;
using Microsoft.Restier.Core.Model;

namespace EasyAFModel
{

    /// <summary>
    /// 
    /// </summary>
    public partial class EasyAFEntitiesModelBuilder : IModelBuilder
    {
    
        #region Public Methods
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        public IEdmModel GetModel(ModelContext context)
        {
            var modelBuilder = new ODataConventionModelBuilder();
            modelBuilder.EntitySet<Inquiry>("Inquiries").IgnoreTrackingFields();
            modelBuilder.EntitySet<InquiryStateType>("InquiryStateTypes").IgnoreTrackingFields();
            modelBuilder.EntitySet<Product>("Products").IgnoreTrackingFields();
            modelBuilder.EntitySet<ProductStatusType>("ProductStatusTypes").IgnoreTrackingFields();
            modelBuilder.EntitySet<User>("Users").IgnoreTrackingFields();
            ExtendModel(modelBuilder);
            return modelBuilder.GetEdmModel();
        }
        
        #endregion
        
        #region Partial Methods
        
        /// <summary>
        /// If implemented outside this generated code, allows for the partial class to register additional resoucres on the model.
        /// </summary>
        /// <param name="modelBuilder">The ODataModelBuilder instance to add models data to.</param>
        partial void ExtendModel(ODataModelBuilder modelBuilder);
        
        #endregion
        
    }
    
}
