//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 9/14/2026 3:48:34 AM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EasyAFModel.Core;
using System.Data.Entity;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Infrastructure;

namespace EasyAFModel
{

    public partial class EasyAFEntities : DbContext
    {
    
        #region Public Properties
        
        public virtual DbSet<Inquiry> Inquiries { get; set; }
        
        public virtual DbSet<InquiryStateType> InquiryStateTypes { get; set; }
        
        public virtual DbSet<Product> Products { get; set; }
        
        public virtual DbSet<ProductStatusType> ProductStatusTypes { get; set; }
        
        public virtual DbSet<User> Users { get; set; }
        
        #endregion
        
        #region Constructors
        
        /// <summary>
        ///
        /// </summary>
        public EasyAFEntities() : base("name=EasyAFEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
        
        /// <summary>
        /// Creates a new <see cref="EasyAFEntities"/> instance for a given connection string.
        /// </summary>
        /// <param name="sqlConnectionString">A SqlClient connection string that does not have EntityClient metadata.</param>
        public EasyAFEntities(string sqlConnectionString) : base(GetEntityConnection(sqlConnectionString), true)
        {
        }
        
        #endregion
        
        #region Private Methods
        
        /// <summary>
        ///
        /// </summary>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="sqlConnectionString">A SqlClient connection string that does not have EntityClient metadata.</param>
        /// <returns>an <see cref="EntityConnection" /> object populated with the default values for an EasyAFEntities EF6 connection.</returns>
        private static EntityConnection GetEntityConnection(string sqlConnectionString)
        {
            var entityBuilder = new EntityConnectionStringBuilder()
            {
                Provider = "Microsoft.Data.SqlClient",
                ProviderConnectionString = sqlConnectionString,
                Metadata = @"res://*/EntityModel.csdl|res://*/EntityModel.ssdl|res://*/EntityModel.msl",
            };
            return new EntityConnection(entityBuilder.ToString());
        }
        
        #endregion
        
    }
    
}
