//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 9/8/2025 8:11:20 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.EasyAF.Restier;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Restier.Core.Authorization;
using System.Linq;
using System.Threading.Tasks;

namespace EasyAFModel.Api.Controllers
{

    /// <summary>
    /// 
    /// </summary>
    public partial class EasyAFEntitiesApi
    {
    
        #region Private Members
        
        private InquiryManager _inquiryManager;
        
        #endregion
        
        #region Public Properties
        
        /// <summary>
        ///
        /// </summary>
        public InquiryManager InquiryManager
        {
            get
            {
                if (_inquiryManager is null)
                {
                    _inquiryManager = ServiceProvider.GetService<InquiryManager>();
                }
                return _inquiryManager;
            }
        }
        
        #endregion
        
        #region Method Authorization
        
        /// <summary>
        ///
        /// </summary>
        protected internal bool CanInsertInquiry() => AuthorizationFactory.ForType<Inquiry>().CanInsertAction();
        
        /// <summary>
        ///
        /// </summary>
        protected internal bool CanUpdateInquiry() => AuthorizationFactory.ForType<Inquiry>().CanUpdateAction();
        
        /// <summary>
        ///
        /// </summary>
        protected internal bool CanDeleteInquiry() => AuthorizationFactory.ForType<Inquiry>().CanDeleteAction();
        
        #endregion
        
        #region EntitySet Filter
        
        /// <summary>
        /// Limits the results of <see cref="Inquiry" /> queries by a pre-determined set of criteria.
        /// </summary>
        protected internal IQueryable<Inquiry> OnFilterInquiries(IQueryable<Inquiry> entitySet)
        {
            RestierHelpers.LogOperation("Inquiry", RestierOperationType.Filtered);
            return InquiryManager.OnFilter(entitySet);
        }
        
        #endregion
        
        #region Interceptors
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="Inquiry" /> instance.</param>
        protected internal async Task OnInsertingInquiryAsync(Inquiry entity)
        {
            await InquiryManager.OnInsertingAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Inserting);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="Inquiry" /> instance.</param>
        protected internal async Task OnInsertedInquiryAsync(Inquiry entity)
        {
            await InquiryManager.OnInsertedAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Inserted);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="Inquiry" /> instance.</param>
        protected internal async Task OnUpdatingInquiryAsync(Inquiry entity)
        {
            await InquiryManager.OnUpdatingAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Updating);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="Inquiry" /> instance.</param>
        protected internal async Task OnUpdatedInquiryAsync(Inquiry entity)
        {
            await InquiryManager.OnUpdatedAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Updated);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="Inquiry" /> instance.</param>
        protected internal async Task OnDeletingInquiryAsync(Inquiry entity)
        {
            await InquiryManager.OnDeletingAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Deleting);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="Inquiry" /> instance.</param>
        protected internal async Task OnDeletedInquiryAsync(Inquiry entity)
        {
            await InquiryManager.OnDeletedAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Deleted);
        }
        
        #endregion
        
    }
    
}
