//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 11/28/2025 7:08:07 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.EasyAF.Restier;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Restier.Core.Authorization;
using System.Linq;
using System.Threading.Tasks;

namespace EasyAFModel.Api.Controllers
{

    /// <summary>
    /// 
    /// </summary>
    public partial class EasyAFEntitiesApi
    {
    
        #region Private Members
        
        private ProductManager _productManager;
        
        #endregion
        
        #region Public Properties
        
        /// <summary>
        ///
        /// </summary>
        public ProductManager ProductManager
        {
            get
            {
                if (_productManager is null)
                {
                    _productManager = ServiceProvider.GetService<ProductManager>();
                }
                return _productManager;
            }
        }
        
        #endregion
        
        #region Method Authorization
        
        /// <summary>
        ///
        /// </summary>
        protected internal bool CanInsertProduct() => AuthorizationFactory.ForType<Product>().CanInsertAction();
        
        /// <summary>
        ///
        /// </summary>
        protected internal bool CanUpdateProduct() => AuthorizationFactory.ForType<Product>().CanUpdateAction();
        
        /// <summary>
        ///
        /// </summary>
        protected internal bool CanDeleteProduct() => AuthorizationFactory.ForType<Product>().CanDeleteAction();
        
        #endregion
        
        #region EntitySet Filter
        
        /// <summary>
        /// Limits the results of <see cref="Product" /> queries by a pre-determined set of criteria.
        /// </summary>
        protected internal IQueryable<Product> OnFilterProducts(IQueryable<Product> entitySet)
        {
            RestierHelpers.LogOperation("Product", RestierOperationType.Filtered);
            return ProductManager.OnFilter(entitySet);
        }
        
        #endregion
        
        #region Interceptors
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="Product" /> instance.</param>
        protected internal async Task OnInsertingProductAsync(Product entity)
        {
            await ProductManager.OnInsertingAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Inserting);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="Product" /> instance.</param>
        protected internal async Task OnInsertedProductAsync(Product entity)
        {
            await ProductManager.OnInsertedAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Inserted);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="Product" /> instance.</param>
        protected internal async Task OnUpdatingProductAsync(Product entity)
        {
            await ProductManager.OnUpdatingAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Updating);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="Product" /> instance.</param>
        protected internal async Task OnUpdatedProductAsync(Product entity)
        {
            await ProductManager.OnUpdatedAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Updated);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="Product" /> instance.</param>
        protected internal async Task OnDeletingProductAsync(Product entity)
        {
            await ProductManager.OnDeletingAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Deleting);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="Product" /> instance.</param>
        protected internal async Task OnDeletedProductAsync(Product entity)
        {
            await ProductManager.OnDeletedAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Deleted);
        }
        
        #endregion
        
    }
    
}
