//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 11/28/2025 7:08:07 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.EasyAF.Restier;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Restier.Core.Authorization;
using System.Linq;
using System.Threading.Tasks;

namespace EasyAFModel.Api.Controllers
{

    /// <summary>
    /// 
    /// </summary>
    public partial class EasyAFEntitiesApi
    {
    
        #region Private Members
        
        private UserManager _userManager;
        
        #endregion
        
        #region Public Properties
        
        /// <summary>
        ///
        /// </summary>
        public UserManager UserManager
        {
            get
            {
                if (_userManager is null)
                {
                    _userManager = ServiceProvider.GetService<UserManager>();
                }
                return _userManager;
            }
        }
        
        #endregion
        
        #region Method Authorization
        
        /// <summary>
        ///
        /// </summary>
        protected internal bool CanInsertUser() => AuthorizationFactory.ForType<User>().CanInsertAction();
        
        /// <summary>
        ///
        /// </summary>
        protected internal bool CanUpdateUser() => AuthorizationFactory.ForType<User>().CanUpdateAction();
        
        /// <summary>
        ///
        /// </summary>
        protected internal bool CanDeleteUser() => AuthorizationFactory.ForType<User>().CanDeleteAction();
        
        #endregion
        
        #region EntitySet Filter
        
        /// <summary>
        /// Limits the results of <see cref="User" /> queries by a pre-determined set of criteria.
        /// </summary>
        protected internal IQueryable<User> OnFilterUsers(IQueryable<User> entitySet)
        {
            RestierHelpers.LogOperation("User", RestierOperationType.Filtered);
            return UserManager.OnFilter(entitySet);
        }
        
        #endregion
        
        #region Interceptors
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="User" /> instance.</param>
        protected internal async Task OnInsertingUserAsync(User entity)
        {
            await UserManager.OnInsertingAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Inserting);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="User" /> instance.</param>
        protected internal async Task OnInsertedUserAsync(User entity)
        {
            await UserManager.OnInsertedAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Inserted);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="User" /> instance.</param>
        protected internal async Task OnUpdatingUserAsync(User entity)
        {
            await UserManager.OnUpdatingAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Updating);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="User" /> instance.</param>
        protected internal async Task OnUpdatedUserAsync(User entity)
        {
            await UserManager.OnUpdatedAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Updated);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="User" /> instance.</param>
        protected internal async Task OnDeletingUserAsync(User entity)
        {
            await UserManager.OnDeletingAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Deleting);
        }
        
        /// <summary>
        ///
        /// </summary>
        /// <param name="entity">The <see cref="User" /> instance.</param>
        protected internal async Task OnDeletedUserAsync(User entity)
        {
            await UserManager.OnDeletedAsync(entity);
            RestierHelpers.LogOperation(entity, RestierOperationType.Deleted);
        }
        
        #endregion
        
    }
    
}
