//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 7/13/2025 4:12:14 AM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.EasyAF.Restier;
using CloudNimble.SimpleMessageBus.Publish;
using EasyAFModel.Core;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Restier.AspNetCore.Model;
using Microsoft.Restier.EntityFramework;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection;

namespace EasyAFModel
{

    /// <summary>
    /// 
    /// </summary>
    public partial class EasyAFEntitiesAdminApi : EasyAFEntityFrameworkApi<EasyAFEntities>
    {
    
        #region Private Members
        
        private InquiryManager _inquiryManager;
        private InquiryStateTypeManager _inquiryStateTypeManager;
        private ProductManager _productManager;
        private ProductStatusTypeManager _productStatusTypeManager;
        private UserManager _userManager;
        
        #endregion
        
        #region Public Properties
        
        /// <summary>
        ///
        /// </summary>
        public InquiryManager InquiryManager
        {
            get
            {
                if (_inquiryManager is null)
                {
                    _inquiryManager = ServiceProvider.GetService<InquiryManager>();
                }
                return _inquiryManager;
            }
        }
        
        /// <summary>
        ///
        /// </summary>
        public InquiryStateTypeManager InquiryStateTypeManager
        {
            get
            {
                if (_inquiryStateTypeManager is null)
                {
                    _inquiryStateTypeManager = ServiceProvider.GetService<InquiryStateTypeManager>();
                }
                return _inquiryStateTypeManager;
            }
        }
        
        /// <summary>
        ///
        /// </summary>
        public ProductManager ProductManager
        {
            get
            {
                if (_productManager is null)
                {
                    _productManager = ServiceProvider.GetService<ProductManager>();
                }
                return _productManager;
            }
        }
        
        /// <summary>
        ///
        /// </summary>
        public ProductStatusTypeManager ProductStatusTypeManager
        {
            get
            {
                if (_productStatusTypeManager is null)
                {
                    _productStatusTypeManager = ServiceProvider.GetService<ProductStatusTypeManager>();
                }
                return _productStatusTypeManager;
            }
        }
        
        /// <summary>
        ///
        /// </summary>
        public UserManager UserManager
        {
            get
            {
                if (_userManager is null)
                {
                    _userManager = ServiceProvider.GetService<UserManager>();
                }
                return _userManager;
            }
        }
        
        #endregion
        
        #region Constructors
        
        /// <summary>
        /// Initializes a new instance of the class.
        /// </summary>
        /// <param name="serviceProvider">The service provider for dependency injection.</param>
        /// <param name="httpContextAccessor">The <see cref="IHttpContextAccessor"/> for the current HTTP context.</param>
        /// <param name="messagePublisher">The <see cref="IMessagePublisher"/> used for publishing messages to SimpleMessageBus.</param>
        /// <param name="logger">The <see cref="ILogger{T}"/> instance for writing log traces.</param>
        public EasyAFEntitiesAdminApi(
            IServiceProvider serviceProvider,
            IHttpContextAccessor httpContextAccessor,
            IMessagePublisher messagePublisher,
            ILogger<EasyAFEntitiesAdminApi> logger)
            : base(serviceProvider, httpContextAccessor, messagePublisher, logger)
        {
        }
        
        #endregion
        
        #region Public Methods
        
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [UnboundOperation]
        public bool IsOnline()
        {
            try
            {
                return DbContext.Database.Exists();
            }
            #pragma warning disable CA1031 // Do not catch general exception types
            catch (Exception ex)
            #pragma warning restore CA1031 // Do not catch general exception types
            {
                Debug.WriteLine(ex);
                return false;
            }
        }
        
        #endregion
        
    }
    
}
