<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net11.0;net10.0;</TargetFrameworks>
        <NoWarn>$(NoWarn);CA1822;EF1001;NU1701;</NoWarn>
        <DisableMSBuildAssemblyCopyCheck>true</DisableMSBuildAssemblyCopyCheck>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Xml.XDocument" Version="4.*" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.*" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net11.0'">
        <!-- Direct reference because the PG team fucked up thir first RC release. https://github.com/npgsql/efcore.pg/issues/3913 -->
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="11.*-*" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="11.*-*" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="11.*-*" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="11.*-*" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="11.*-*" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="11.*-*" />
        <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="11.*-*" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="11.*-*" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="11.*-*" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="11.*-*" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.*" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.*" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.*" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.*" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.*" />
        <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.*" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.*" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.*" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.*" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CloudNimble.EasyAF.MSBuild\CloudNimble.EasyAF.MSBuild.csproj" />
    </ItemGroup>

</Project>
