//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 11/20/2024 11:29:16 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.EasyAF.Business;
using CloudNimble.SimpleMessageBus.Publish;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace EasyAFModel.Managers
{

    /// <summary>
    /// 
    /// </summary>
    public partial class ProductManager : StatusEntityManager<EasyAFEntities, Product, Guid, ProductStatusType>
    {
    
        #region Constructors
        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="dataContext"></param>
        /// <param name="messagePublisher"></param>
        public ProductManager(EasyAFEntities dataContext, IMessagePublisher messagePublisher) : base(dataContext, messagePublisher)
        {
        }
        
        #endregion
        
        #region Public Methods
        
        /// <summary>
        /// Limits the results of <see cref="Product" /> queries by a pre-determined set of criteria.
        /// </summary>
        public IQueryable<Product> OnFilter(IQueryable<Product> entitySet)
        {
            OnFilterInternal(ref entitySet);
            return entitySet;
        }
        
        #region Object Validation
        
        /// <summary>
        /// Validate the Product before it is inserted into the database.
        /// </summary>
        /// <param name="entity">The <see cref="Product" /> instance that is being inserted.</param>
        public override async Task OnInsertingAsync(Product entity)
        {
            Initialize();
            await base.OnInsertingAsync(entity);
            OnInsertingInternal(entity);
        }
        
        /// <summary>
        /// Validate the Product before it is updated in the database.
        /// </summary>
        /// <param name="entity">The <see cref="Product" /> instance that is being updated.</param>
        public override async Task OnUpdatingAsync(Product entity)
        {
            Initialize();
            await base.OnUpdatingAsync(entity);
            OnUpdatingInternal(entity);
        }
        
        /// <summary>
        /// Validate the Product before it is deleted from the database.
        /// </summary>
        /// <param name="entity">The <see cref="Product" /> instance that is being deleted.</param>
        public override async Task OnDeletingAsync(Product entity)
        {
            Initialize();
            await base.OnDeletingAsync(entity);
            OnDeletingInternal(entity);
        }
        
        #endregion
        
        #endregion
        
        #region Partial Methods
        
        /// <summary>
        /// If implemented outside this generated code, allows for additional business logic to run to further reduce the amount of data returned from the request.
        /// </summary>
        /// <param name="entitySet">The DbSet that needs to be filtered.</param>
        /// <param name="clientAppId">If implemented, allows you to totally change the shape of the data based on the application calling this API.</param>
        partial void OnFilterInternal(ref IQueryable<Product> entitySet, string clientAppId = null);
        
        /// <summary>
        /// If implemented outside this generated code, allows for additional business logic to run before the Product is committed to the database.
        /// </summary>
        /// <param name="entity">The <see cref="Product" /> instance that is being committed to the database.</param>
        partial void OnInsertingInternal(Product entity);
        
        /// <summary>
        /// If implemented outside this generated code, allows for additional business logic to run before Product edits are committed to the database.
        /// </summary>
        /// <param name="entity">The <see cref="Product" /> instance that is being edited.</param>
        partial void OnUpdatingInternal(Product entity);
        
        /// <summary>
        /// If implemented outside this generated code, allows for additional business logic to run before the Product is deleted from the database.
        /// </summary>
        /// <param name="entity">The <see cref="Product" /> instance being committed to the database.</param>
        partial void OnDeletingInternal(Product entity);
        
        #endregion
        
    }
    
}
