//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 11/28/2025 12:03:51 AM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.SimpleMessageBus.Core;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;

namespace EasyAFModel
{

/// <summary>
/// Base class for entity-based messages in the SimpleMessageBus system.
/// </summary>
/// <typeparam name="T">The type of entity contained in the message.</typeparam>
public abstract class DbEntityMessageBase<T> : MessageBase where T : class
{

        #region Properties
        
        /// <summary>
        /// Gets or sets the entity associated with this message.
        /// </summary>
        public T Entity { get; set; }
        
        #endregion
        
        #region Constructors
        
        /// <summary>
        /// Initializes a new instance of the <see cref="DbEntityMessageBase{T}"/> class.
        /// </summary>
        protected DbEntityMessageBase() : base()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="DbEntityMessageBase{T}"/> class with a parent message.
        /// </summary>
        /// <param name="parent">The parent message for correlation.</param>
        protected DbEntityMessageBase(IMessage parent) : base(parent)
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="DbEntityMessageBase{T}"/> class with metadata.
        /// </summary>
        /// <param name="triggeredById">The ID of the user who triggered this message.</param>
        /// <param name="correlationSource">The source system or service that generated this message.</param>
        protected DbEntityMessageBase(string triggeredById, string correlationSource) : base()
        {
            if (!string.IsNullOrWhiteSpace(triggeredById))
            {
                Metadata["User.Id"] = triggeredById;
            }
            
            if (!string.IsNullOrWhiteSpace(correlationSource))
            {
                Metadata["Correlation.Source"] = correlationSource;
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="DbEntityMessageBase{T}"/> class with a parent message and metadata.
        /// </summary>
        /// <param name="parent">The parent message for correlation.</param>
        /// <param name="triggeredById">The ID of the user who triggered this message.</param>
        /// <param name="correlationSource">The source system or service that generated this message.</param>
        protected DbEntityMessageBase(IMessage parent, string triggeredById, string correlationSource) : base(parent)
        {
            if (!string.IsNullOrWhiteSpace(triggeredById))
            {
                Metadata["User.Id"] = triggeredById;
            }
            
            if (!string.IsNullOrWhiteSpace(correlationSource))
            {
                Metadata["Correlation.Source"] = correlationSource;
            }
        }
        
        #endregion
        
    }
    
}
