//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 11/27/2025 5:36:59 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.SimpleMessageBus.Core;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;

namespace EasyAFModel
{

/// <summary>
/// Message published when a <see cref="InquiryStateType"/> entity is deleted.
/// </summary>
public class InquiryStateTypeDeleted : DbEntityMessageBase<InquiryStateType>
{

        #region Constructors
        
        /// <summary>
        /// Initializes a new instance of the <see cref="InquiryStateTypeDeleted"/> class.
        /// </summary>
        public InquiryStateTypeDeleted() : base()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="InquiryStateTypeDeleted"/> class with a parent message.
        /// </summary>
        /// <param name="parent">The parent message for correlation.</param>
        public InquiryStateTypeDeleted(IMessage parent) : base(parent)
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="InquiryStateTypeDeleted"/> class with the deleted entity.
        /// </summary>
        /// <param name="entity">The <see cref="InquiryStateType"/> entity that was deleted.</param>
        public InquiryStateTypeDeleted(InquiryStateType entity) : this()
        {
            Entity = entity;
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="InquiryStateTypeDeleted"/> class with the deleted entity and a parent message.
        /// </summary>
        /// <param name="entity">The <see cref="InquiryStateType"/> entity that was deleted.</param>
        /// <param name="parent">The parent message for correlation.</param>
        public InquiryStateTypeDeleted(InquiryStateType entity, IMessage parent) : base(parent)
        {
            Entity = entity;
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="InquiryStateTypeDeleted"/> class with the deleted entity and metadata.
        /// </summary>
        /// <param name="entity">The <see cref="InquiryStateType"/> entity that was deleted.</param>
        /// <param name="triggeredById">The ID of the user who triggered this message.</param>
        /// <param name="correlationSource">The source system or service that generated this message.</param>
        public InquiryStateTypeDeleted(InquiryStateType entity, string triggeredById, string correlationSource) : base(triggeredById, correlationSource)
        {
            Entity = entity;
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="InquiryStateTypeDeleted"/> class with the deleted entity, parent message, and metadata.
        /// </summary>
        /// <param name="entity">The <see cref="InquiryStateType"/> entity that was deleted.</param>
        /// <param name="parent">The parent message for correlation.</param>
        /// <param name="triggeredById">The ID of the user who triggered this message.</param>
        /// <param name="correlationSource">The source system or service that generated this message.</param>
        public InquiryStateTypeDeleted(InquiryStateType entity, IMessage parent, string triggeredById, string correlationSource) : base(parent, triggeredById, correlationSource)
        {
            Entity = entity;
        }
        
        #endregion
        
    }
    
}
