//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 9/8/2025 8:11:20 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.SimpleMessageBus.Core;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;

namespace EasyAFModel
{

/// <summary>
/// Message published when a <see cref="Product"/> entity is updated.
/// </summary>
public class ProductUpdated : DbEntityMessageBase<Product>
{

        #region Properties
        
        /// <summary>
        /// Gets or sets the dictionary of updated property values.
        /// </summary>
        public Dictionary<string, object> UpdatedValues { get; set; }
        
        #endregion
        
        #region Constructors
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductUpdated"/> class.
        /// </summary>
        public ProductUpdated() : base()
        {
            UpdatedValues = new Dictionary<string, object>();
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductUpdated"/> class with a parent message.
        /// </summary>
        /// <param name="parent">The parent message for correlation.</param>
        public ProductUpdated(IMessage parent) : base(parent)
        {
            UpdatedValues = new Dictionary<string, object>();
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductUpdated"/> class with the updated entity and changed values.
        /// </summary>
        /// <param name="entity">The <see cref="Product"/> entity that was updated.</param>
        /// <param name="updatedValues">The dictionary of property values that were changed.</param>
        public ProductUpdated(Product entity, Dictionary<string, object> updatedValues) : this()
        {
            Entity = entity;
            UpdatedValues = updatedValues ?? new Dictionary<string, object>();
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductUpdated"/> class with the updated entity, changed values, and parent message.
        /// </summary>
        /// <param name="entity">The <see cref="Product"/> entity that was updated.</param>
        /// <param name="updatedValues">The dictionary of property values that were changed.</param>
        /// <param name="parent">The parent message for correlation.</param>
        public ProductUpdated(Product entity, Dictionary<string, object> updatedValues, IMessage parent) : base(parent)
        {
            Entity = entity;
            UpdatedValues = updatedValues ?? new Dictionary<string, object>();
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductUpdated"/> class with the updated entity, changed values, and metadata.
        /// </summary>
        /// <param name="entity">The <see cref="Product"/> entity that was updated.</param>
        /// <param name="updatedValues">The dictionary of property values that were changed.</param>
        /// <param name="triggeredById">The ID of the user who triggered this message.</param>
        /// <param name="correlationSource">The source system or service that generated this message.</param>
        public ProductUpdated(Product entity, Dictionary<string, object> updatedValues, string triggeredById, string correlationSource) : base(triggeredById, correlationSource)
        {
            Entity = entity;
            UpdatedValues = updatedValues ?? new Dictionary<string, object>();
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductUpdated"/> class with the updated entity, changed values, parent message, and metadata.
        /// </summary>
        /// <param name="entity">The <see cref="Product"/> entity that was updated.</param>
        /// <param name="updatedValues">The dictionary of property values that were changed.</param>
        /// <param name="parent">The parent message for correlation.</param>
        /// <param name="triggeredById">The ID of the user who triggered this message.</param>
        /// <param name="correlationSource">The source system or service that generated this message.</param>
        public ProductUpdated(Product entity, Dictionary<string, object> updatedValues, IMessage parent, string triggeredById, string correlationSource) : base(parent, triggeredById, correlationSource)
        {
            Entity = entity;
            UpdatedValues = updatedValues ?? new Dictionary<string, object>();
        }
        
        #endregion
        
    }
    
}
