//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 11/27/2025 5:36:59 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.SimpleMessageBus.Core;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;

namespace EasyAFModel
{

/// <summary>
/// Message published when a new <see cref="ProductStatusType"/> entity is created.
/// </summary>
public class ProductStatusTypeCreated : DbEntityMessageBase<ProductStatusType>
{

        #region Constructors
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductStatusTypeCreated"/> class.
        /// </summary>
        public ProductStatusTypeCreated() : base()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductStatusTypeCreated"/> class with a parent message.
        /// </summary>
        /// <param name="parent">The parent message for correlation.</param>
        public ProductStatusTypeCreated(IMessage parent) : base(parent)
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductStatusTypeCreated"/> class with the created entity.
        /// </summary>
        /// <param name="entity">The <see cref="ProductStatusType"/> entity that was created.</param>
        public ProductStatusTypeCreated(ProductStatusType entity) : this()
        {
            Entity = entity;
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductStatusTypeCreated"/> class with the created entity and a parent message.
        /// </summary>
        /// <param name="entity">The <see cref="ProductStatusType"/> entity that was created.</param>
        /// <param name="parent">The parent message for correlation.</param>
        public ProductStatusTypeCreated(ProductStatusType entity, IMessage parent) : base(parent)
        {
            Entity = entity;
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductStatusTypeCreated"/> class with the created entity and metadata.
        /// </summary>
        /// <param name="entity">The <see cref="ProductStatusType"/> entity that was created.</param>
        /// <param name="triggeredById">The ID of the user who triggered this message.</param>
        /// <param name="correlationSource">The source system or service that generated this message.</param>
        public ProductStatusTypeCreated(ProductStatusType entity, string triggeredById, string correlationSource) : base(triggeredById, correlationSource)
        {
            Entity = entity;
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductStatusTypeCreated"/> class with the created entity, parent message, and metadata.
        /// </summary>
        /// <param name="entity">The <see cref="ProductStatusType"/> entity that was created.</param>
        /// <param name="parent">The parent message for correlation.</param>
        /// <param name="triggeredById">The ID of the user who triggered this message.</param>
        /// <param name="correlationSource">The source system or service that generated this message.</param>
        public ProductStatusTypeCreated(ProductStatusType entity, IMessage parent, string triggeredById, string correlationSource) : base(parent, triggeredById, correlationSource)
        {
            Entity = entity;
        }
        
        #endregion
        
    }
    
}
