//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 9/8/2025 8:11:20 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.SimpleMessageBus.Core;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;

namespace EasyAFModel
{

/// <summary>
/// Message published when a <see cref="Product"/> entity is deleted.
/// </summary>
public class ProductDeleted : DbEntityMessageBase<Product>
{

        #region Constructors
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductDeleted"/> class.
        /// </summary>
        public ProductDeleted() : base()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductDeleted"/> class with a parent message.
        /// </summary>
        /// <param name="parent">The parent message for correlation.</param>
        public ProductDeleted(IMessage parent) : base(parent)
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductDeleted"/> class with the deleted entity.
        /// </summary>
        /// <param name="entity">The <see cref="Product"/> entity that was deleted.</param>
        public ProductDeleted(Product entity) : this()
        {
            Entity = entity;
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductDeleted"/> class with the deleted entity and a parent message.
        /// </summary>
        /// <param name="entity">The <see cref="Product"/> entity that was deleted.</param>
        /// <param name="parent">The parent message for correlation.</param>
        public ProductDeleted(Product entity, IMessage parent) : base(parent)
        {
            Entity = entity;
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductDeleted"/> class with the deleted entity and metadata.
        /// </summary>
        /// <param name="entity">The <see cref="Product"/> entity that was deleted.</param>
        /// <param name="triggeredById">The ID of the user who triggered this message.</param>
        /// <param name="correlationSource">The source system or service that generated this message.</param>
        public ProductDeleted(Product entity, string triggeredById, string correlationSource) : base(triggeredById, correlationSource)
        {
            Entity = entity;
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductDeleted"/> class with the deleted entity, parent message, and metadata.
        /// </summary>
        /// <param name="entity">The <see cref="Product"/> entity that was deleted.</param>
        /// <param name="parent">The parent message for correlation.</param>
        /// <param name="triggeredById">The ID of the user who triggered this message.</param>
        /// <param name="correlationSource">The source system or service that generated this message.</param>
        public ProductDeleted(Product entity, IMessage parent, string triggeredById, string correlationSource) : base(parent, triggeredById, correlationSource)
        {
            Entity = entity;
        }
        
        #endregion
        
    }
    
}
