//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 11/27/2025 10:23:25 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CloudNimble.SimpleMessageBus.Core;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;

namespace EasyAFModel
{

/// <summary>
/// Message published when a new <see cref="User"/> entity is created.
/// </summary>
public class UserCreated : DbEntityMessageBase<User>
{

        #region Constructors
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UserCreated"/> class.
        /// </summary>
        public UserCreated() : base()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UserCreated"/> class with a parent message.
        /// </summary>
        /// <param name="parent">The parent message for correlation.</param>
        public UserCreated(IMessage parent) : base(parent)
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UserCreated"/> class with the created entity.
        /// </summary>
        /// <param name="entity">The <see cref="User"/> entity that was created.</param>
        public UserCreated(User entity) : this()
        {
            Entity = entity;
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UserCreated"/> class with the created entity and a parent message.
        /// </summary>
        /// <param name="entity">The <see cref="User"/> entity that was created.</param>
        /// <param name="parent">The parent message for correlation.</param>
        public UserCreated(User entity, IMessage parent) : base(parent)
        {
            Entity = entity;
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UserCreated"/> class with the created entity and metadata.
        /// </summary>
        /// <param name="entity">The <see cref="User"/> entity that was created.</param>
        /// <param name="triggeredById">The ID of the user who triggered this message.</param>
        /// <param name="correlationSource">The source system or service that generated this message.</param>
        public UserCreated(User entity, string triggeredById, string correlationSource) : base(triggeredById, correlationSource)
        {
            Entity = entity;
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UserCreated"/> class with the created entity, parent message, and metadata.
        /// </summary>
        /// <param name="entity">The <see cref="User"/> entity that was created.</param>
        /// <param name="parent">The parent message for correlation.</param>
        /// <param name="triggeredById">The ID of the user who triggered this message.</param>
        /// <param name="correlationSource">The source system or service that generated this message.</param>
        public UserCreated(User entity, IMessage parent, string triggeredById, string correlationSource) : base(parent, triggeredById, correlationSource)
        {
            Entity = entity;
        }
        
        #endregion
        
    }
    
}
