<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net11.0;net10.0;netstandard2.0;</TargetFrameworks>
        <NoWarn>$(NoWarn);CA1822;</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CloudNimble.EasyAF.Core\CloudNimble.EasyAF.Core.csproj" />
    </ItemGroup>

</Project>
