using CloudNimble.Breakdance.AspNetCore;
using CloudNimble.EasyAF.Configuration;
using CloudNimble.EasyAF.Http.OData;
using CloudNimble.EasyAF.OData;
using CloudNimble.EasyAF.Tests.OData.Fakes;
using FluentAssertions;
using Microsoft.AspNet.OData.Extensions;
using Microsoft.AspNet.OData.Query;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Restier.Breakdance;
using Microsoft.Restier.Core;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Simple.OData.Client;
using System;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace CloudNimble.EasyAF.Tests.OData
{

    /// <summary>
    /// Tests functionality of the <see cref="ApiClient"/> using a fake Restier API.
    /// </summary>
    [TestClass]
    public class ApiClientTests : RestierBreakdanceTestBase<FakeApi>
    {

        #region Test Orchestration

        /// <summary>
        /// Constructor with service configuration.
        /// </summary>
        public ApiClientTests()
        {
            TestHostBuilder.ConfigureServices(services =>
            {
                // we need to use a delegate function here because the TestServer does not exist at the time the services are configured.
                services.AddSingleton<IHttpClientFactory>(new FakeHttpClientFactory(() =>
                {
                    var httpClient = TestServer?.CreateClient();
                    httpClient.BaseAddress = new Uri($"http://localhost/{WebApiConstants.RoutePrefix}");
                    return httpClient;
                }));
                services.AddSingleton(new ConfigurationBase { ApiClientName = "TestClient", ApiRoot = WebApiConstants.RoutePrefix });
                services.AddSingleton<ApiClient>();

            });

            AddRestierAction = (apiBuilder) =>
            {
                apiBuilder.AddRestierApi<FakeApi>(restierServices =>
                {
                    restierServices
                        .AddEFCoreProviderServices<FakeContext>()
                        .AddSingleton(new ODataValidationSettings
                        {
                            MaxTop = 5,
                            MaxAnyAllExpressionDepth = 3,
                            MaxExpansionDepth = 3,
                        });

                    using var tempServices = restierServices.BuildServiceProvider();

                    var scopeFactory = tempServices.GetService<IServiceScopeFactory>();
                    using var scope = scopeFactory.CreateScope();
                    var dbContext = scope.ServiceProvider.GetService<FakeContext>();

                    // EnsureCreated() returns false if the database already exists
                    if (dbContext.Database.EnsureCreated())
                    {
                        FakeContext.Seed(dbContext);
                    }
                });
            };

            MapRestierAction = (routeBuilder) =>
            {
                routeBuilder.MapApiRoute<FakeApi>(WebApiConstants.RouteName, WebApiConstants.RoutePrefix);
            };
        }

        /// <summary>
        /// Test initialization.
        /// </summary>
        [TestInitialize]
        public void TestInitialize() => TestSetup();

        /// <summary>
        /// Test cleanup.
        /// </summary>
        [TestCleanup]
        public void TearDown() => TestTearDown();

        #endregion

        /// <summary>
        /// Tests that DI works property when configuring the <see cref="TestServer"/>.
        /// </summary>
        [TestMethod]
        public void ApiClientTests_HasExpectedState()
        {
            TestServer.Should().NotBeNull();
            TestServer.Services.Should().NotBeNull();
            GetService<IConfiguration>().Should().NotBeNull();
            var factory = TestServer.Services.GetRequiredService<IServiceScopeFactory>();
            factory.Should().NotBeNull();
        }

        /// <summary>
        /// Tests that the <see cref="TestServer"/> can generate an <see cref="HttpRequest"/> directly.
        /// </summary>
        /// <returns></returns>
        [TestMethod]
        public async Task ApiClientTests_HttpClient_ShouldReturnRootContent()
        {
            var client = GetHttpClient();
            client.Should().NotBeNull();
            var result = await client.GetAsync("");
            result.StatusCode.Should().Be(HttpStatusCode.OK);
            var resultContent = await result.Content.ReadAsStringAsync();
            resultContent.Should().ContainAll("$metadata", "Entities");
        }

        /// <summary>
        /// Tests that the <see cref="HttpClient"/> generated by the <see cref="TestServer"/> can query the API.
        /// </summary>
        /// <returns></returns>
        [TestMethod]
        public async Task ApiClientTests_HttpClient_CanQueryEntities()
        {
            var httpClient = GetHttpClient();
            httpClient.Should().NotBeNull();
            var result = await httpClient.GetAsync(new Uri($"http://localhost/{WebApiConstants.RoutePrefix}entities"));
            result.StatusCode.Should().Be(HttpStatusCode.OK);

            var (response, errorContent) = await result.DeserializeResponseAsync<ODataV4ResultList<FakeEntity>>();
            errorContent.Should().BeNull();
            response.Items.Count.Should().NotBe(0);
        }

        /// <summary>
        /// Tests that the <see cref="ApiClient"/> can query the API.
        /// </summary>
        /// <returns></returns>
        [TestMethod]
        public async Task ApiClientTests_ApiClient_CanQueryEntities()
        {
            var oDataClient = GetService<ApiClient>();
            oDataClient.Should().NotBeNull();
            var entities = await oDataClient.For<FakeEntity>("Entities").FindEntriesAsync();
            entities.Should().NotBeNull();
            entities.Should().NotHaveCount(0);
        }

        /// <summary>
        /// Tests that the <see cref="ApiClient"/> throws the expected <see cref="UnresolvableObjectException"/> when an invalid action is called.
        /// </summary>
        [TestMethod]
        public void ApiClientTests_ApiClient_ThrowsExceptionOnMissingAction()
        {
            var oDataClient = GetService<ApiClient>();
            oDataClient.Should().NotBeNull();
            Action act = () =>
            {
                oDataClient.Unbound().Action("SomeMissingAction").ExecuteAsScalarAsync<bool>().GetAwaiter().GetResult();
            };
            act.Should().ThrowExactly<UnresolvableObjectException>().WithMessage("Action [SomeMissingAction] not found");
        }

        /// <summary>
        /// Tests that the <see cref="ApiClient"/> does not expose internal exception details.
        /// </summary>
        [TestMethod]
        public void ApiClientTests_ApiClient_HidesInternalExceptionDetails()
        {
            var oDataClient = GetService<ApiClient>();
            oDataClient.Should().NotBeNull();
            Action act = () =>
            {
                oDataClient.Unbound().Action("SomeFaultyAction()").ExecuteAsync().GetAwaiter().GetResult();
            };
            // unfortunately, the client cannot receive details of an internal exception, so this is all we get
            // better do some loging in your API to try and catch this, but on the bright-side, the client isn't
            //    exposing the details of your internal troubles to potential callers
            act.Should().ThrowExactly<WebRequestException>().WithMessage("Bad Request");
        }

        /// <summary>
        /// Tests that the <see cref="ApiClient"/> does not throw an exception when a record is not found.
        /// </summary>
        /// <remarks>
        /// This is a configuration setting in the <see cref="ODataClientSettingsHelper"/> that we use to set to this behavior.
        /// The default behavior in the <see cref="ODataClient"/> is to throw an exception.
        /// </remarks>
        [TestMethod]
        public void ApiClientTests_ApiClient_DoesNotThrowExceptionOnNotFound()
        {
            var oDataClient = GetService<ApiClient>();
            oDataClient.Should().NotBeNull();
            FakeEntity entity = null;
            Action act = () =>
            {
                entity = oDataClient.For<FakeEntity>("Entities").Filter(c => c.Id == 999).FindEntryAsync().GetAwaiter().GetResult();
            };
            act.Should().NotThrow<WebRequestException>();
            entity.Should().BeNull();
        }

    }

}
