using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace CloudNimble.EasyAF.CodeGen.Generators.Base
{

    /// <summary>
    /// 
    /// </summary>
    public abstract class CodeGeneratorBase : IDisposable
    {

        #region Private Members

        private StringWriter _baseWriter;
        internal IndentedTextWriter _writer;
        private string header =
            """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by EasyAF's Code Generators.
            //     Date Generated: {0}
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            """;

        #endregion

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>
        public HashSet<string> ExtraUsings { get; private set; }

        /// <summary>
        /// 
        /// </summary>
        public bool IsGenerated { get; internal set; }

        /// <summary>
        /// 
        /// </summary>
        public string Namespace { get; set; }

        #endregion

        #region Constructors

        /// <summary>
        /// 
        /// </summary>
        /// <param name="extraUsings"></param>
        /// <param name="namespaceName"></param>
        public CodeGeneratorBase(List<string> extraUsings, string namespaceName)
        {
            _baseWriter = new StringWriter();
            _writer = new IndentedTextWriter(_baseWriter, "    ")
            {
                Indent = 0
            };
            ExtraUsings = new HashSet<string>(extraUsings ?? new List<string>());
            Namespace = namespaceName;
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// Sets the Indent to 1, writes the Summary tag, the Class declaration, and then the opening bracket.
        /// </summary>
        /// <param name="declaration">The full Class declaration string.</param>
        /// <param name="summaryText">The test to put inside the &lt;summary&gt; tag.</param>
        public void ClassBegin(string declaration, string summaryText)
        {
            _writer.Indent = 1;
            _writer.WriteLine("/// <summary>");
            _writer.WriteLine($"/// {summaryText}");
            _writer.WriteLine("/// </summary>");
            SectionBegin(declaration, 1);
        }

        /// <summary>
        /// Writes the end of a Class.
        /// </summary>
        public void ClassEnd()
        {
            SectionEnd(1);
        }

        /// <summary>
        /// 
        /// </summary>
        public abstract void Generate();

        /// <summary>
        /// 
        /// </summary>
        public void Header()
        {
            _writer.Write(header, DateTime.Now);
            _writer.WriteLine();
            _writer.WriteLine();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="namespaceName"></param>
        public void NamespaceBegin(string namespaceName)
        {
            SectionBegin($"namespace {namespaceName}", 0);
        }

        /// <summary>
        /// 
        /// </summary>
        public void NamespaceEnd()
        {
            SectionEnd(0, false);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="regionName"></param>
        public void RegionBegin(string regionName)
        {
            _writer.Indent = 2;
            _writer.WriteLine($"#region {regionName}");
            _writer.WriteLine();
        }

        /// <summary>
        /// 
        /// </summary>
        public void RegionEnd()
        {
            _writer.Indent = 2;
            _writer.WriteLine($"#endregion");
            _writer.WriteLine();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return _baseWriter.ToString();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="usingName"></param>
        /// <returns></returns>
        public void Using(string usingName)
        {
            _writer.WriteLine($"using {usingName};");
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="directory"></param>
        /// <param name="addSuffix"></param>
        /// <param name="name"></param>
        /// <returns>A string containing the path of the file that was created.</returns>
        internal string WriteFile(string name, string directory = null, bool addSuffix = true)
        {
            var path = Path.Combine(directory ?? Directory.GetCurrentDirectory(), $"{name}{(addSuffix ? ".Generated.cs" : "")}");
            Generate();
            File.WriteAllText(path, ToString());
            return path;
        }

        #endregion

        #region Private Methods

        /// <summary>
        /// 
        /// </summary>
        internal void SectionBegin(string sectionText, int indentLevel = 2)
        {
            _writer.Indent = indentLevel;
            _writer.WriteLine(sectionText);
            _writer.WriteLine("{");
            _writer.WriteLine();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="indentLevel">The number of levels to indent. Defaults to 2, which is the class member level.</param>
        /// <param name="trailingBlankLine"></param>
        internal void SectionEnd(int indentLevel = 2, bool trailingBlankLine = true)
        {
            _writer.Indent = indentLevel;
            _writer.WriteLine("}");
            if (trailingBlankLine) _writer.WriteLine();
        }

        /// <summary>
        /// 
        /// </summary>
        internal void WriteUsings()
        {
            foreach (var use in ExtraUsings.OrderBy(c => c))
            {
                Using(use);
            }
            _writer.WriteLine();
        }

        #endregion

        #region IDisposable Implementation

        /// <summary>
        /// 
        /// </summary>
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="disposing"></param>
        protected virtual void Dispose(bool disposing)
        {
            if (disposing)
            {
                // free managed resources
                if (_writer is not null)
                {
                    _writer.Dispose();
                    _writer = null;
                }
                if (_baseWriter is not null)
                {
                    _baseWriter.Dispose();
                    _baseWriter = null;
                }
            }
        }

        #endregion

    }

}
