//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EasyAF's Code Generators.
//     Date Generated: 12/1/2024 3:22:47 AM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(EasyAFModel.EasyAFEntities),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets03f5ea902738d05d2282c1a00ece91fe3329a17a05e9231beddf414896dd43b7))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework 6 Power Tools", "0.9.5.0")]
    internal sealed class ViewsForBaseEntitySets03f5ea902738d05d2282c1a00ece91fe3329a17a05e9231beddf414896dd43b7 : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "03f5ea902738d05d2282c1a00ece91fe3329a17a05e9231beddf414896dd43b7"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent is null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "EasyAFModelStoreContainer.Products")
            {
                return GetView0();
            }

            if (extentName == "EasyAFModelStoreContainer.ProductStatusTypes")
            {
                return GetView1();
            }

            if (extentName == "EasyAFEntities.Products")
            {
                return GetView2();
            }

            if (extentName == "EasyAFEntities.ProductStatusTypes")
            {
                return GetView3();
            }

            if (extentName == "EasyAFModelStoreContainer.Users")
            {
                return GetView4();
            }

            if (extentName == "EasyAFModelStoreContainer.Inquiries")
            {
                return GetView5();
            }

            if (extentName == "EasyAFModelStoreContainer.InquiryStateTypes")
            {
                return GetView6();
            }

            if (extentName == "EasyAFEntities.Users")
            {
                return GetView7();
            }

            if (extentName == "EasyAFEntities.Inquiries")
            {
                return GetView8();
            }

            if (extentName == "EasyAFEntities.InquiryStateTypes")
            {
                return GetView9();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for EasyAFModelStoreContainer.Products.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Products
        [EasyAFModel.Store.Products](T1.Products_Id, T1.Products_DisplayName, T1.Products_StatusTypeId, T1.Products_CreatedById, T1.Products_DateCreated, T1.Products_UpdatedById, T1.Products_DateUpdated)
    FROM (
        SELECT 
            T.Id AS Products_Id, 
            T.DisplayName AS Products_DisplayName, 
            T.StatusTypeId AS Products_StatusTypeId, 
            T.CreatedById AS Products_CreatedById, 
            T.DateCreated AS Products_DateCreated, 
            T.UpdatedById AS Products_UpdatedById, 
            T.DateUpdated AS Products_DateUpdated, 
            True AS _from0
        FROM EasyAFEntities.Products AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EasyAFModelStoreContainer.ProductStatusTypes.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ProductStatusTypes
        [EasyAFModel.Store.ProductStatusTypes](T1.ProductStatusTypes_Id, T1.ProductStatusTypes_DisplayName, T1.ProductStatusTypes_SortOrder, T1.ProductStatusTypes_IsActive, T1.ProductStatusTypes_CreatedById, T1.ProductStatusTypes_DateCreated, T1.ProductStatusTypes_UpdatedById, T1.ProductStatusTypes_DateUpdated)
    FROM (
        SELECT 
            T.Id AS ProductStatusTypes_Id, 
            T.DisplayName AS ProductStatusTypes_DisplayName, 
            T.SortOrder AS ProductStatusTypes_SortOrder, 
            T.IsActive AS ProductStatusTypes_IsActive, 
            T.CreatedById AS ProductStatusTypes_CreatedById, 
            T.DateCreated AS ProductStatusTypes_DateCreated, 
            T.UpdatedById AS ProductStatusTypes_UpdatedById, 
            T.DateUpdated AS ProductStatusTypes_DateUpdated, 
            True AS _from0
        FROM EasyAFEntities.ProductStatusTypes AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EasyAFEntities.Products.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Products
        [EasyAFModel.Product](T1.Product_Id, T1.Product_DisplayName, T1.Product_StatusTypeId, T1.Product_CreatedById, T1.Product_DateCreated, T1.Product_UpdatedById, T1.Product_DateUpdated)
    FROM (
        SELECT 
            T.Id AS Product_Id, 
            T.DisplayName AS Product_DisplayName, 
            T.StatusTypeId AS Product_StatusTypeId, 
            T.CreatedById AS Product_CreatedById, 
            T.DateCreated AS Product_DateCreated, 
            T.UpdatedById AS Product_UpdatedById, 
            T.DateUpdated AS Product_DateUpdated, 
            True AS _from0
        FROM EasyAFModelStoreContainer.Products AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EasyAFEntities.ProductStatusTypes.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ProductStatusTypes
        [EasyAFModel.ProductStatusType](T1.ProductStatusType_Id, T1.ProductStatusType_DisplayName, T1.ProductStatusType_SortOrder, T1.ProductStatusType_IsActive, T1.ProductStatusType_CreatedById, T1.ProductStatusType_DateCreated, T1.ProductStatusType_UpdatedById, T1.ProductStatusType_DateUpdated)
    FROM (
        SELECT 
            T.Id AS ProductStatusType_Id, 
            T.DisplayName AS ProductStatusType_DisplayName, 
            T.SortOrder AS ProductStatusType_SortOrder, 
            T.IsActive AS ProductStatusType_IsActive, 
            T.CreatedById AS ProductStatusType_CreatedById, 
            T.DateCreated AS ProductStatusType_DateCreated, 
            T.UpdatedById AS ProductStatusType_UpdatedById, 
            T.DateUpdated AS ProductStatusType_DateUpdated, 
            True AS _from0
        FROM EasyAFModelStoreContainer.ProductStatusTypes AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EasyAFModelStoreContainer.Users.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Users
        [EasyAFModel.Store.Users](T1.Users_Id, T1.Users_FirstName, T1.Users_LastName, T1.Users_CreatedById, T1.Users_DateCreated)
    FROM (
        SELECT 
            T.Id AS Users_Id, 
            T.FirstName AS Users_FirstName, 
            T.LastName AS Users_LastName, 
            T.CreatedById AS Users_CreatedById, 
            T.DateCreated AS Users_DateCreated, 
            True AS _from0
        FROM EasyAFEntities.Users AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EasyAFModelStoreContainer.Inquiries.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Inquiries
        [EasyAFModel.Store.Inquiries](T1.Inquiries_Id, T1.Inquiries_Subject, T1.Inquiries_Message, T1.Inquiries_StateTypeId, T1.Inquiries_CreatedById, T1.Inquiries_DateCreated, T1.Inquiries_UpdatedById, T1.Inquiries_DateUpdated)
    FROM (
        SELECT 
            T.Id AS Inquiries_Id, 
            T.Subject AS Inquiries_Subject, 
            T.Message AS Inquiries_Message, 
            T.StateTypeId AS Inquiries_StateTypeId, 
            T.CreatedById AS Inquiries_CreatedById, 
            T.DateCreated AS Inquiries_DateCreated, 
            T.UpdatedById AS Inquiries_UpdatedById, 
            T.DateUpdated AS Inquiries_DateUpdated, 
            True AS _from0
        FROM EasyAFEntities.Inquiries AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EasyAFModelStoreContainer.InquiryStateTypes.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing InquiryStateTypes
        [EasyAFModel.Store.InquiryStateTypes](T1.InquiryStateTypes_Id, T1.InquiryStateTypes_DisplayName, T1.InquiryStateTypes_SortOrder, T1.InquiryStateTypes_InstructionText, T1.InquiryStateTypes_PrimaryTargetSortOrder, T1.InquiryStateTypes_PrimaryTargetDisplayText, T1.InquiryStateTypes_SecondaryTargetSortOrder, T1.InquiryStateTypes_SecondaryTargetDisplayText, T1.InquiryStateTypes_IsActive, T1.InquiryStateTypes_CreatedById, T1.InquiryStateTypes_UpdatedById, T1.InquiryStateTypes_DateCreated, T1.InquiryStateTypes_DateUpdated)
    FROM (
        SELECT 
            T.Id AS InquiryStateTypes_Id, 
            T.DisplayName AS InquiryStateTypes_DisplayName, 
            T.SortOrder AS InquiryStateTypes_SortOrder, 
            T.InstructionText AS InquiryStateTypes_InstructionText, 
            T.PrimaryTargetSortOrder AS InquiryStateTypes_PrimaryTargetSortOrder, 
            T.PrimaryTargetDisplayText AS InquiryStateTypes_PrimaryTargetDisplayText, 
            T.SecondaryTargetSortOrder AS InquiryStateTypes_SecondaryTargetSortOrder, 
            T.SecondaryTargetDisplayText AS InquiryStateTypes_SecondaryTargetDisplayText, 
            T.IsActive AS InquiryStateTypes_IsActive, 
            T.CreatedById AS InquiryStateTypes_CreatedById, 
            T.UpdatedById AS InquiryStateTypes_UpdatedById, 
            T.DateCreated AS InquiryStateTypes_DateCreated, 
            T.DateUpdated AS InquiryStateTypes_DateUpdated, 
            True AS _from0
        FROM EasyAFEntities.InquiryStateTypes AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EasyAFEntities.Users.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Users
        [EasyAFModel.User](T1.User_Id, T1.User_FirstName, T1.User_LastName, T1.User_CreatedById, T1.User_DateCreated)
    FROM (
        SELECT 
            T.Id AS User_Id, 
            T.FirstName AS User_FirstName, 
            T.LastName AS User_LastName, 
            T.CreatedById AS User_CreatedById, 
            T.DateCreated AS User_DateCreated, 
            True AS _from0
        FROM EasyAFModelStoreContainer.Users AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EasyAFEntities.Inquiries.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Inquiries
        [EasyAFModel.Inquiry](T1.Inquiry_Id, T1.Inquiry_Subject, T1.Inquiry_Message, T1.Inquiry_StateTypeId, T1.Inquiry_CreatedById, T1.Inquiry_DateCreated, T1.Inquiry_UpdatedById, T1.Inquiry_DateUpdated)
    FROM (
        SELECT 
            T.Id AS Inquiry_Id, 
            T.Subject AS Inquiry_Subject, 
            T.Message AS Inquiry_Message, 
            T.StateTypeId AS Inquiry_StateTypeId, 
            T.CreatedById AS Inquiry_CreatedById, 
            T.DateCreated AS Inquiry_DateCreated, 
            T.UpdatedById AS Inquiry_UpdatedById, 
            T.DateUpdated AS Inquiry_DateUpdated, 
            True AS _from0
        FROM EasyAFModelStoreContainer.Inquiries AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EasyAFEntities.InquiryStateTypes.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing InquiryStateTypes
        [EasyAFModel.InquiryStateType](T1.InquiryStateType_Id, T1.InquiryStateType_DisplayName, T1.InquiryStateType_SortOrder, T1.InquiryStateType_InstructionText, T1.InquiryStateType_PrimaryTargetSortOrder, T1.InquiryStateType_PrimaryTargetDisplayText, T1.InquiryStateType_SecondaryTargetSortOrder, T1.InquiryStateType_SecondaryTargetDisplayText, T1.InquiryStateType_IsActive, T1.InquiryStateType_CreatedById, T1.InquiryStateType_UpdatedById, T1.InquiryStateType_DateCreated, T1.InquiryStateType_DateUpdated)
    FROM (
        SELECT 
            T.Id AS InquiryStateType_Id, 
            T.DisplayName AS InquiryStateType_DisplayName, 
            T.SortOrder AS InquiryStateType_SortOrder, 
            T.InstructionText AS InquiryStateType_InstructionText, 
            T.PrimaryTargetSortOrder AS InquiryStateType_PrimaryTargetSortOrder, 
            T.PrimaryTargetDisplayText AS InquiryStateType_PrimaryTargetDisplayText, 
            T.SecondaryTargetSortOrder AS InquiryStateType_SecondaryTargetSortOrder, 
            T.SecondaryTargetDisplayText AS InquiryStateType_SecondaryTargetDisplayText, 
            T.IsActive AS InquiryStateType_IsActive, 
            T.CreatedById AS InquiryStateType_CreatedById, 
            T.UpdatedById AS InquiryStateType_UpdatedById, 
            T.DateCreated AS InquiryStateType_DateCreated, 
            T.DateUpdated AS InquiryStateType_DateUpdated, 
            True AS _from0
        FROM EasyAFModelStoreContainer.InquiryStateTypes AS T
    ) AS T1");
        }
    }
}
