//using CloudNimble.Breakdance.AspNetCore;
//using CloudNimble.EasyAF.Data;
//using CloudNimble.EasyAF.Restier.Breakdance;
//using CloudNimble.EasyAF.Tests.Restier.Api;
//using CloudNimble.SimpleMessageBus.Core;
//using CloudNimble.SimpleMessageBus.Publish;
//using EasyAFModel;
//using EasyAFModel.Managers;
//using Microsoft.AspNet.OData.Query;
//using Microsoft.AspNetCore.Builder;
//using Microsoft.Extensions.Configuration;
//using Microsoft.Extensions.DependencyInjection;
//using Microsoft.Restier.Core;
//using Microsoft.Restier.Core.Model;
//using Microsoft.VisualStudio.TestTools.UnitTesting;
//using System.Data.Entity;
//using System.Security.Claims;

//namespace CloudNimble.EasyAF.Tests.Restier
//{

//    /// <summary>
//    /// Base class for setting up unit tests against the BurnRate APIs.
//    /// </summary>
//    public class EasyAFContextApiTestBase : EasyAFRestierTestBase<EasyAFEntitiesApi>
//    {

//        #region Properties

//        /// <summary>
//        /// A reference to the current <see cref="TestContext"/>.
//        /// </summary>
//        public TestContext TestContext { get; set; }

//        #endregion

//        #region Constructors

//        /// <summary>
//        /// Constructs the test environment to simulate the BurnRate APIs.
//        /// </summary>
//        public EasyAFContextApiTestBase() : base()
//        {

//            ApplicationBuilderAction = (app) =>
//            {
//                app.UseResponseCompression();
//                //app.UseHttpsRedirection();
//                app.UseRestierBatching();
//            };

//            // configure services needed by the test host
//            TestHostBuilder.ConfigureServices((builder, services) =>
//            {

//                // these services need to be configured to support authentication and the Microsoft.Data.SqlClient in the API
//                DbConfiguration.SetConfiguration(new EasyAFSqlAzureConfiguration());
//                EasyAF_ClaimsPrincipalExtensions.Initialize();
//                AuthorizationHelper.Configure();

//                services
//                    //.AddHttpsRedirection(options => options.HttpsPort = 443)
//                    .AddHttpContextAccessor()
//                    .AddOptions()
//                    .AddResponseCompression()
//                    .AddCors();

//                // add a DbContext for test setup / teardown
//                services.AddScoped(_ => new EasyAFEntities(builder.Configuration["ConnectionStrings:EasyAFEntities"]));

//            });

//            // configure services needed by Restier
//            AddRestierAction = (apiBuilder) =>
//            {
//                apiBuilder.AddRestierApi<EasyAFEntitiesApi>(routeServices =>
//                {
//                    var config = GetService<IConfiguration>();
//                    routeServices
//                        .AddOptions()
//                        .Configure<AzureStorageQueueOptions>(config.GetSection("AzureStorageQueueOptions"))
//                        .AddScoped(_ => new EasyAFEntities(config["ConnectionStrings:EasyAFEntities"]))
//                        .AddEF6ProviderServices<EasyAFEntities>()
//                        .AddChainedService<IModelBuilder, EasyAFEntitiesModelBuilder>()
//                        .AddSingleton(new ODataValidationSettings
//                        {
//                            MaxTop = 100,
//                            MaxAnyAllExpressionDepth = 4,
//                            MaxExpansionDepth = 4
//                        })
//                        .AddSingleton<IMessagePublisher, AzureStorageQueueMessagePublisher>()
//                        .AddScoped<ProductManager>();
//                });
//            };

//            MapRestierAction = (routeBuilder) =>
//            {
//                // 1. this code is correctly setting the root path for the API to http://localhost/api/tests
//                // 2. the BaseAddress in the HttpClient generated by the TestServer is correctly "api/tests"
//                // 3. client.GetAsync() returns a 404 showing a request path http://localhost/api/[the-request]
//                //    ?? why is it not respecting the full root path?
//                // 4. if I set up the GetHttpClient() below with $"{WebApiConstants.RoutePrefix}/" then it works
//                //    so something in the TestServer is stripping off the "test" part of the path if I don't add the trailing "/"
//                routeBuilder.MapApiRoute<EasyAFEntitiesApi>(WebApiConstants.RouteName, WebApiConstants.RoutePrefix);
//            };

//        }

//        #endregion

//    }

//}
